name: Review meeting
description: Minutes from review meeting.
title: Monthly review
labels: [
  "Review Meeting",
]
body:
  - type: input
    id: description
    attributes:
      label: "Call to order"
      description: "List participants"
      placeholder: "@user1, @user2"
    validations:
      required: true
  - type: checkboxes
    id: agenda
    attributes:
      label: "Agenda & Minutes"
      description: Go through the items below, create new issues as necessary, and tick the boxes along the way. Add minutes to section below, referring to new issues using the `#XX` syntax. 
      options:
        - label: Adjust the statement of applicability according to any issues resolved since last meeting. For example, if a new policy was implemented, update status and add link to the policy.
          required: true
        - label: Review issues not resolved since last meeting and find out how to help the new responsible persons if necessary. Describe outcomes below.
          required: true
        - label: Review incident reports and add new risks to the risk log. Any risk with a score higher than 12 needs to be addressed with a [contingency_plan.yml](contingency_plan.yml) issue. 
          required: true
        - label: Review the risk log and (optionally) open issues for risks that should be addressed before next meeting.
          required: true
  - type: textarea
    id: minutes
    attributes:
      label: "Minutes"
      description: Short and explicit description of other business discussed at the meeting. Bullet lists are fine.
  - type: textarea
    id: any-other-business
    attributes:
      label: "Any other business"
      description: Short and explicit description of other business discussed at the meeting. Bullet lists are fine.
